// packages/svelte-pack/components/viewers/PhotoViewer.svelte
<div class="MP-viewer" role="button" tabindex="-1" title="Podgląd zdjęcia - kliknij by zamknąć">
  <button title="Zamknij podgląd" id="close-viewer"></button>
  <img bind:this="{img}" class="viewed-photo" alt="Powiększone zdjęcie" />
</div>

<script lang="ts">
  import { mixin, type GlobalConfigI } from "@matb85/base-pack";
  import { getContext, onMount } from "svelte";

  let img = $state<HTMLImageElement>()!;

  const GlobalConfig: GlobalConfigI = getContext("svelte-pack-sizes");

  onMount(() => {
    const base = new mixin(img, img.parentElement!, GlobalConfig);
    window.addEventListener("enlargePhoto", event => base.mounted((event as CustomEvent).detail));

    window.addEventListener("keyup", e => {
      if (e.key === "Escape") base.close();
    });

    img.parentElement!.addEventListener("click", () => base.close());
  });
</script>

// packages/vue-pack/src/components/PhotoViewer.vue
<template>
  <div class="MP-viewer" role="button" tabindex="-1" title="Podgląd zdjęcia - kliknij by zamknąć">
    <button title="Zamknij podgląd" id="close-viewer"></button>
    <img ref="img" class="viewed-photo" alt="Powiększone zdjęcie" />
  </div>
</template>

<script setup lang="ts">
import { onMounted, useTemplateRef } from "vue";
import { mixin } from "@matb85/base-pack";
import { useVuePackStore } from "../piniaStore";

const store = useVuePackStore();
const GlobalConfig = store.vuepacksizes!;

const trigger = "vuepack-enlargephoto";
const img = useTemplateRef<HTMLImageElement>("img");

onMounted(() => {
  window.addEventListener(trigger, event => mixin.mounted((event as CustomEvent).detail, img.value!.parentElement!, img.value!, GlobalConfig));

  window.addEventListener("keyup", e => {
    if (e.key == "Escape") mixin.close(img.value!.parentElement!, img.value!);
  });
  img.value!.parentElement!.addEventListener("click", () => mixin.close(img.value!.parentElement!, img.value!));
});
</script>
