// packages/vue-pack/src/components/Map.vue
<template>
  <section ref="root" aria-label="Mapa Google" role="application" data-observerhandler="map"></section>
</template>

<script setup lang="ts">
import { type MapCallback, mapUtil } from "@matb85/base-pack";
import { onMounted, useTemplateRef } from "vue";
import { useVuePackStore } from "../piniaStore";

const store = useVuePackStore();

const root = useTemplateRef<HTMLElement>("root");

const props = defineProps<{
  apikey: string;
  callback: MapCallback;
}>();

onMounted(() => {
  store.addHandler({
    name: "map",
    handler: () => mapUtil(props.apikey, props.callback, root.value!),
  });
  store.state!.observer.observe(root.value!);
});
</script>

// packages/svelte-pack/components/Map.svelte
<section bind:this="{map}" class="{className}" aria-label="Mapa Google" data-observerhandler="map"></section>

<script lang="ts">
  import { onMount } from "svelte";
  import { type MapCallback, mapUtil, mutations } from "@matb85/base-pack";

  let map = $state<HTMLElement>()!;

  interface Props {
    className?: any;
    apikey?: string;
    callback?: MapCallback;
  }

  let { className = null, apikey = "", callback = m => console.log(m) }: Props = $props();

  onMount(() => {
    mutations.addHandler(window.sveltepack, {
      name: "map",
      handler: () => mapUtil(apikey, callback, map),
    });
    window.sveltepack.observer.observe(map);
  });
</script>
