// packages/svelte-pack/components/PhotoViewer.svelte
<div class="MP-viewer" role="button" tabindex="-1" title="Podgląd zdjęcia - kliknij by zamknąć">
  <button title="Zamknij podgląd" id="close-viewer"></button>
  <img bind:this="{img}" class="viewed-photo" alt="Powiększone zdjęcie" />
</div>

<script lang="ts">
  import { type GlobalConfigI, mixin } from "@matb85/base-pack";
  import { getContext, onMount } from "svelte";

  let img = $state<HTMLImageElement>()!;

  const GlobalConfig: GlobalConfigI = getContext("svelte-pack-sizes");

  onMount(() => {
    window.addEventListener("enlargePhoto", event => mixin.mounted((event as CustomEvent).detail, img.parentElement!, img, GlobalConfig));

    window.addEventListener("keyup", e => {
      if (e.key === "Escape") mixin.close(img.parentElement!, img);
    });

    img.parentElement!.addEventListener("click", () => mixin.close(img.parentElement!, img));
  });
</script>

// packages/vue-pack/src/components/Viewers/PhotoViewer.vue
<template>
  <div class="MP-viewer" role="button" tabindex="-1" title="Podgląd zdjęcia - kliknij by zamknąć">
    <button title="Zamknij podgląd" id="close-viewer"></button>
    <img ref="img" class="viewed-photo" alt="Powiększone zdjęcie" />
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { mixin } from "@matb85/base-pack";
import { useVuePackStore } from "../../piniaStore";

const store = useVuePackStore();
const GlobalConfig = store.vuepacksizes;

const trigger = "vuepack-enlargephoto";
const img = ref<HTMLImageElement>(null);

onMounted(() => {
  const base = new mixin(img.value, img.value.parentElement, GlobalConfig);
  window.addEventListener(trigger, data => base.mounted(data.detail));

  window.addEventListener("keyup", e => {
    if (e.key == "Escape") base.close();
  });
  img.value.parentElement.addEventListener("click", () => base.close());
});
</script>
