// packages/svelte-pack/components/Photo.svelte
<div class="medium-pack-photo {className}" bind:this="{el}" on:click="{enlarge}">
  <img
    bind:this="{img}"
    src="{src}"
    data-src="{src}"
    data-srcset="{genSrcset}"
    sizes="{genSizes}"
    alt="{alt}"
    data-group="{group}"
    data-observerhandler="photo" />
  <span class="cross"></span>
</div>

<script>
import { onMount } from "svelte";
import { photo, mutations } from "@matb85/base-pack";
import { getContext } from "svelte";

export let src;
export let alt = undefined;
export let sizes = undefined;
export let prevent = [];
export let multiview = false;
export let group = undefined;
export let className = "";
// bingings to DOM elements
let img, el;

// setup sizes & srcset
const settings = photo(src, getContext("svelte-pack-sizes"), sizes);
let genSrcset = settings.genSrcset,
  genSizes = settings.genSizes;

// update srcset on change
function updateSrc() {
  if (typeof window == "undefined" || typeof img == "undefined") return;
  genSrcset = photo(src, getContext("svelte-pack-sizes"), sizes).genSrcset;
  if (img.classList.contains("loaded")) img.srcset = genSrcset;
}
$: updateSrc() || src;

function enlarge() {
  if (!img.classList.contains("loaded") || prevent.includes("enlargeonclick")) return;
  const enlarger = !multiview ? "enlargePhoto" : "enlargeManyPhotos";
  window.dispatchEvent(new CustomEvent(enlarger, { detail: { rect: el.getBoundingClientRect(), img } }));
}
// dispatching/adding to the store
function dispatch() {
  const detail = { src, srcset: genSrcset, group, ratio: img.naturalWidth / img.naturalHeight, alt };
  mutations.addphoto(window.sveltepack, detail);

  window.sveltepack.observer.observe(img);
}

onMount(() => {
  if (prevent.includes("addtolist")) return;
  if (img.complete) {
    dispatch();
  } else {
    img.addEventListener("load", () => dispatch(), { once: true });
  }
});
</script>

// src/components/Photo.vue
<template>
  <div class="medium-pack-photo" @click="enlarge">
    <img ref="img" :src="src" :data-srcset="srcset" :sizes="sizes" :alt="alt" data-observerhandler="photo" />
    <span class="cross"></span>
  </div>
</template>

<script>
export default {
  name: "Photo",
  props: {
    src: String,
    alt: String,
    sizes: String,
    srcset: String,
    dontenlargeonclick: String,
    dontaddtolist: String,
    multiview: String,
  },
  methods: {
    enlarge() {
      if (!this.$refs.img.classList.contains("loaded") || typeof this.dontenlargeonclick !== "undefined") return;
      const enlarger = typeof this.multiview === "undefined" ? "enlargePhoto" : "enlargeManyPhotos";
      this.$root.$emit(enlarger, { rect: this.$el.getBoundingClientRect(), img: this.$refs.img });
    },
  },
  mounted() {
    const img = this.$refs.img;

    if (typeof this.dontaddtolist === "undefined")
      img.addEventListener(
        "load",
        () =>
          this.$store.commit("vuepack/addphoto", {
            src: this.src,
            srcset: this.srcset,
            ratio: img.naturalWidth / img.naturalHeight,
          }),
        { once: true }
      );
    this.$store.state.vuepack.observer.observe(img);
  },
};
</script>

<style lang="scss">
@mixin wh($dim: 100%) {
  width: $dim;
  height: $dim;
}

.medium-pack-photo {
  display: block;
  position: relative;
  overflow: hidden;
  > img {
    display: block;
    object-fit: cover;
    @include wh;
    transition: 0.4s transform, 0.4s filter;
    filter: blur(3vw) brightness(100%);
    transform: scale(1.05);
  }
  &:not(.no-hover) > img {
    cursor: zoom-in;
  }
  > img.loaded {
    filter: blur(0vw) brightness(100%);
    transform: scale(1);
  }
  &:not(.no-hover):hover {
    > img.loaded {
      transform: scale(1.05);
      filter: blur(0vw) brightness(60%);
    }
    > img.loaded + .cross {
      opacity: 1;
      transform: rotate(180deg);
    }
  }
}
.medium-pack-photo .cross {
  $dim: 8rem;
  $offset: calc(50% - #{$dim/2});
  left: $offset;
  top: $offset;
  @include wh($dim);
  display: block;
  position: absolute;
  opacity: 0;
  transition: transform 0.4s, opacity 0.4s;
  &::before,
  &::after {
    position: absolute;
    left: 50%;
    content: " ";
    height: 100%;
    width: 0.4px;
    background-color: white;
  }
  &::after {
    transform: rotate(90deg);
  }
}
</style>
