// packages/svelte-pack/components/nav/Footer.svelte
<footer class="footer {className}">
  <div class="footer-bg">
    <Photo prevent="{['enlargeonclick']}" src="{background}" sizes="{[720, 1290, 1920, 2400]}" className="no-hover" />
    <div class="footer-text">
      <slot />
    </div>
  </div>
  <div class="footer-links">
    {#each references as reference}
      <div v-for="reference in references" :key="reference.id" class="footer-links-col">
        <h3>{reference.name}</h3>
        {#each reference.links as link}
          <ul>
            <li>
              <a href="{link.url}">{link.name}</a>
            </li>
          </ul>
        {/each}
      </div>
    {/each}
  </div>
  <slot name="above-copyright" />
  <div class="footer-copyright">Copyright © {name} {new Date().getFullYear()}</div>
</footer>

<script>
import Photo from "../Photo.svelte";
export let className;
export let name;
export let background;
export let references;
</script>

// packages/vue-pack/src/components/nav/Footer.vue
<template>
  <footer class="footer">
    <div class="footer-bg">
      <Photo dontenlargeonclick :src="background" :sizes="[720, 1290, 1920, 2400]" class="w-full h-96 no-hover" />
      <div class="footer-text">
        <slot />
      </div>
    </div>
    <div class="footer-links">
      <div v-for="reference in references" :key="reference.id" class="footer-links-col">
        <h3>{{ reference.name }}</h3>
        <ul v-for="link in reference.links" :key="link.id">
          <li>
            <a :href="link.url">{{ link.name }}</a>
          </li>
        </ul>
      </div>
    </div>
    <slot name="above-copyright" />
    <div class="footer-copyright">Copyright © {{ name }} {{ new Date().getFullYear() }}</div>
  </footer>
</template>

<script>
import Photo from "../Photo.vue";
export default {
  name: "Footer",
  components: { Photo },
  props: {
    name: String,
    background: String,
    references: Array,
  },
};
</script>
