// packages/svelte-pack/components/nav/Navbar.svelte
<nav class="navbar {className}">
  <slot name="logo" />
  <div class="nav" style="{isActive ? 'transform: translateX(-100%)' : ''}">
    <slot />
  </div>
  <div
    class="hamburger-container"
    on:click="{() => {
      isActive = !isActive;
    }}">
    <div class="hamburger {isActive ? 'is-active' : ''}">
      <div class="hamburger-inner"></div>
    </div>
  </div>
</nav>

<script>
export let className = "";
let isActive = false;
</script>

// packages/vue-pack/src/components/nav/Navbar.vue
<template>
  <nav class="navbar">
    <slot name="logo"></slot>
    <div class="nav" :style="isActive ? 'transform: translateX(-100%)' : ''">
      <slot></slot>
    </div>
    <div class="hamburger-container" @click="isActive = !isActive">
      <div class="hamburger" :class="{ 'is-active': isActive }">
        <div class="hamburger-inner"></div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  data: () => ({ isActive: false }),
};
</script>
